read.csv("dete1234.csv",header=T)->data0
data0
plot(prop~age,type="b",
data=subset(data0,item=="gyokai"),
xlab="年齢",ylab="割合(%)",
xlim=c(20,80),ylim=c(0,0.2),col="blue")
lines(prop~age,type="b",
data=subset(data0,item=="niku"),
col="red")
lines(prop~age,type="b",
data=subset(data0,item=="kome"),
col="green")
lines(prop~age,type="b",
data=subset(data0,item=="pan"),
col="yellow")
abline(h=0,v=0)
legend(10,80,c("魚介類","肉類","米","パン"),
lty=c(1,1),pch=c(1,1),
col=c("red","blue","green","yellow"))
legend?
help(legend)

